---
title: "p8105_hw6_RYW2109"
author: "Rita Wang"
date: "2024-12-02"
output: github_document
---
```{r default_setting, echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
library(tidyverse)
library(ggplot2)
library(purrr)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

```{r q1_data, echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
data_file = "./data"

if (!dir.exists(data_file)) {
  dir.create(data_file)
}
weather_df = 
  rnoaa::meteo_pull_monitors(
      # install.packages("rnoaa") --> "package ‘rnoaa’ is not available for this version of R"
      # 1. install.packages("remotes")
      # 2. remotes::install_github("ropensci/rnoaa")
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything()) 

# Save your data frame to the new directory
file_path = file.path(data_file, "weather_data.csv")
write.csv(weather_df, file_path, row.names = FALSE)

weather_df
```

```{r q1, echo = FALSE, message = FALSE, warning = FALSE}

```

```{r q2_data, echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
  # importing data
url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/refs/heads/master/homicide-data.csv"

file_path = file.path(data_file, "homicide-data.csv")
download.file(url, destfile = file_path, method = "libcurl")

data_original = read.csv(file_path) %>% 
  janitor::clean_names()
```

```{r q2_a, echo = FALSE, message = FALSE, warning = FALSE}
data_df1 = data_original %>% 
  mutate(
    city_state = paste(city, state, sep = ", ")
  )

data_df2 = data_df1 %>%
  group_by(city_state) %>%
  summarise(
    total_homicides = n(),
    unsolved_homicides = sum(disposition %in% c("Closed without arrest", "Open/No arrest")),
    .groups = "drop"
  )
```
